version: "3"
services:

  patientinfo:
    image: patient_info:1.0
    build:
      context: .
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/mediscreen?serverTimezone=Europe/Paris
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootroot
    ports:
      - "8081:8081"

  mysql_db:
    image: "mysql:8.0"
#    volumes:
#      - mysql_db_data:/var/lib/mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_ROOT_PASSWORD: rootroot


#volumes:
#  db_data: {}