#version: "3"
#services:
#  patientinfo:
#    image: "patient_info:1.0"
#    restart: always
#    ports:
#      - "8081:8081"
#
#  clientui:
#    depends_on:
#      - patientinfo
#    image: client_ui:1.0
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    restart: always
